#!/usr/bin/env python3
# -*-coding:UTF-8 -*

import os
import sys

import secrets

sys.path.append(os.path.join(os.environ['AIL_BIN'], 'packages/'))
sys.path.append('./modules/')

from Role_Manager import create_user_db, get_default_admin_token


if __name__ == "__main__":

    username = 'admin@admin.test'
    password = secrets.token_urlsafe()
    create_user_db(username, password, role='admin', default=True)
    token = get_default_admin_token()

    default_passwd_file = os.path.join(os.environ['AIL_HOME'], 'DEFAULT_PASSWORD')
    to_write_str = '# Password Generated by default\n# This file is deleted after the first login\n#\nemail=admin@admin.test\npassword='
    to_write_str = to_write_str + password + '\nAPI_Key=' + token
    with open(default_passwd_file, 'w') as f:
        f.write(to_write_str)

    print('new user created: {}'.format(username))
    print('password: {}'.format(password))
